// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcrepo

import (
	"database/sql"
)

type Container struct {
	ID            string
	DockerID      string
	ImageName     string
	ContainerName string
	GitRepo       sql.NullString
	UserID        string
	EnvVars       sql.NullString
	Ports         sql.NullString
}

type Port struct {
	Port        int64
	InUse       bool
	ContainerID sql.NullString
}

type Template struct {
	ID         string
	Name       string
	RepoName   string
	Dockerfile string
}

type Token struct {
	Token  string
	UserID string
}

type User struct {
	ID       string
	Username string
	Password string
}
